# -*- coding: utf-8 -*-
"""Backbone: DenseNet121.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWQvjKrfkHcAzpts3wOZAcAzdOIEb495
"""

"""
FractureNet — Multi-task: Classification + Segmentation
Backbone: DenseNet121 | Dataset: FracAtlas
"""

#  1. IMPORTS
import subprocess
subprocess.run(['pip', 'install', '-q', 'albumentations'], check=False)

import os, json, zipfile, random, warnings, glob
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
from tqdm import tqdm
warnings.filterwarnings('ignore')

import cv2
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model, regularizers
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.utils.class_weight import compute_class_weight
import seaborn as sns
import albumentations as A
from collections import Counter
import csv

print(f"TensorFlow : {tf.__version__}")
print(f"GPU        : {tf.config.list_physical_devices('GPU')}")

# ─────────────────────────── 2. CONFIGURATION ────────────────────────────────
IMG_SIZE      = (224, 224)
BATCH_SIZE    = 16
EPOCHS        = 30
SEED          = 42
LR_PHASE1     = 1e-3
LR_PHASE2     = 5e-5
L2_REG        = 1e-4
CLS_THRESHOLD = 0.35
SEG_THRESHOLD = 0.5

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ['PYTHONHASHSEED'] = str(SEED)

IMG_H, IMG_W = IMG_SIZE
tf.keras.mixed_precision.set_global_policy('mixed_float16')
print(f"Mixed Precision : {tf.keras.mixed_precision.global_policy().name}")

#  3. LOAD DATASET
try:
    from google.colab import drive
    if not os.path.exists('/content/drive/MyDrive'):
        print("Mounting Google Drive...")
        drive.mount('/content/drive', force_remount=False)
        print("Google Drive mounted ")
    else:
        print("Google Drive already mounted ")
except Exception as e:
    print(f"Drive not available: {e}")

def find_zip_file(verbose=True):
    priority_dirs = ['/content', '/content/drive/MyDrive', '/content/drive/My Drive']
    keywords      = ['fracatlas', 'frac', 'archive', '32']
    candidates_all, candidates_pref = [], []

    for d in priority_dirs:
        if not os.path.exists(d):
            continue
        try:
            for fname in os.listdir(d):
                if fname.lower().endswith('.zip'):
                    full = os.path.join(d, fname)
                    candidates_all.append(full)
                    if any(kw in fname.lower() for kw in keywords):
                        candidates_pref.append(full)
        except PermissionError:
            pass

    if not candidates_all:
        if verbose: print("  Deep search in Drive...")
        for pattern in ['/content/drive/**/*frac*.zip',
                        '/content/drive/**/*archive*.zip',
                        '/content/drive/**/*.zip']:
            results = glob.glob(pattern, recursive=True)
            if results:
                candidates_all.extend(results)
                pref = [r for r in results if any(kw in r.lower() for kw in keywords)]
                candidates_pref.extend(pref)
                if candidates_pref: break

    ordered = candidates_pref if candidates_pref else candidates_all
    for path in ordered:
        if os.path.exists(path):
            if verbose:
                size_mb = os.path.getsize(path) / 1024**2
                print(f"   Found: {path}  ({size_mb:.1f} MB)")
            return path
    return None

print("\nSearching for dataset ZIP...")
ZIP_PATH = find_zip_file(verbose=True)

if ZIP_PATH is None:
    print("\nZIP not found — uploading manually...")
    try:
        from google.colab import files
        uploaded = files.upload()
        for fname in uploaded:
            dest = f'/content/{fname}'
            with open(dest, 'wb') as f:
                f.write(uploaded[fname])
            ZIP_PATH = dest
            break
    except Exception as e:
        raise FileNotFoundError(f"Dataset ZIP not found.\n{e}")

print(f"\nZIP path: {ZIP_PATH}")

#  4. EXTRACT
EXTRACT_ROOT = '/content/extracted_dataset'
os.makedirs(EXTRACT_ROOT, exist_ok=True)
with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    z.extractall(EXTRACT_ROOT)
print("Extraction complete")

DATASET_DIR = None
for root, dirs, _ in os.walk(EXTRACT_ROOT):
    if 'FracAtlas' in dirs:
        DATASET_DIR = os.path.join(root, 'FracAtlas'); break
    if os.path.basename(root) == 'FracAtlas':
        DATASET_DIR = root; break
if DATASET_DIR is None:
    for root, dirs, _ in os.walk(EXTRACT_ROOT):
        if 'images' in dirs:
            DATASET_DIR = root; break

FRAC_DIR    = os.path.join(DATASET_DIR, 'images', 'Fractured')
NONFRAC_DIR = os.path.join(DATASET_DIR, 'images', 'Non_fractured')
COCO_PATH   = os.path.join(DATASET_DIR, 'Annotations', 'COCO JSON', 'COCO_fracture_masks.json')

for p in [FRAC_DIR, NONFRAC_DIR, COCO_PATH]:
    if not os.path.exists(p):
        raise FileNotFoundError(f"Missing: {p}")
print(f"Dataset: {DATASET_DIR}")

#  5. NORMALIZE IMAGES
def normalize_images(folder, target_ext='.jpg'):
    converted = 0
    for fname in os.listdir(folder):
        fpath = os.path.join(folder, fname)
        ext   = os.path.splitext(fname)[1].lower()
        if ext not in ['.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp']:
            continue
        try:
            img = Image.open(fpath).convert('RGB')
            if ext != target_ext:
                new_path = os.path.splitext(fpath)[0] + target_ext
                img.save(new_path, 'JPEG', quality=95)
                os.remove(fpath)
                converted += 1
        except Exception as e:
            print(f"Skipping {fname}: {e}")
    print(f"  Converted {converted} files in {os.path.basename(folder)}")

normalize_images(FRAC_DIR)
normalize_images(NONFRAC_DIR)

#  6. COCO ANNOTATIONS
with open(COCO_PATH, 'r') as f:
    coco_data = json.load(f)

id_to_img     = {img['id']: img for img in coco_data['images']}
fname_to_anns = {}
for ann in coco_data['annotations']:
    img_info = id_to_img[ann['image_id']]
    fname    = img_info['file_name']
    fname_to_anns.setdefault(fname, []).append({
        'bbox'        : ann['bbox'],
        'segmentation': ann['segmentation'],
        'orig_w'      : img_info['width'],
        'orig_h'      : img_info['height'],
    })
print(f"Loaded {len(coco_data['annotations'])} annotations for {len(fname_to_anns)} images")

#  7. BUILD DATA LIST
VALID_EXTS    = ('.jpg', '.jpeg', '.png')
frac_files    = [f for f in os.listdir(FRAC_DIR)    if f.lower().endswith(VALID_EXTS)]
nonfrac_files = [f for f in os.listdir(NONFRAC_DIR) if f.lower().endswith(VALID_EXTS)]
total         = len(frac_files) + len(nonfrac_files)

print(f"\nFractured    : {len(frac_files):>5}  ({100*len(frac_files)/total:.1f}%)")
print(f"Non-Fractured: {len(nonfrac_files):>5}  ({100*len(nonfrac_files)/total:.1f}%)")
print(f"Total        : {total:>5}")

fname_to_bp = {}
CSV_PATH = os.path.join(DATASET_DIR, 'dataset.csv')
if os.path.exists(CSV_PATH):
    with open(CSV_PATH, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get('mixed', '0') == '1':
                bp = 'mixed'
            else:
                bps = [b for b in ['hand', 'leg', 'hip', 'shoulder'] if row.get(b, '0') == '1']
                bp  = bps[0] if bps else 'unknown'
            fname_to_bp[row['image_id']] = bp

all_data = []
for f in frac_files:
    bp = fname_to_bp.get(f, 'unknown')
    all_data.append({'path': os.path.join(FRAC_DIR, f), 'label': 1, 'fname': f,
                     'bp': bp, 'combined_label': f"1_{bp}"})
for f in nonfrac_files:
    bp = fname_to_bp.get(f, 'unknown')
    all_data.append({'path': os.path.join(NONFRAC_DIR, f), 'label': 0, 'fname': f,
                     'bp': bp, 'combined_label': f"0_{bp}"})
random.shuffle(all_data)

#  8. TRAIN / VAL / TEST SPLIT
labels_all  = [d['combined_label'] for d in all_data]
counts      = Counter(labels_all)
safe_labels = [l if counts[l] >= 4 else f"{l.split('_')[0]}_rare" for l in labels_all]

train_data, temp_data = train_test_split(all_data, test_size=0.30,
                                          stratify=safe_labels, random_state=SEED)
labels_temp = [d['combined_label'] for d in temp_data]
counts_temp = Counter(labels_temp)
safe_temp   = [l if counts_temp[l] >= 2 else f"{l.split('_')[0]}_rare" for l in labels_temp]
val_data, test_data = train_test_split(temp_data, test_size=0.50,
                                        stratify=safe_temp, random_state=SEED)
print(f"Train:{len(train_data)} | Val:{len(val_data)} | Test:{len(test_data)}")

#  9. AUGMENTATION
aug_train = A.Compose([
    A.Resize(IMG_H, IMG_W),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.3),
    A.RandomRotate90(p=0.3),
    A.ShiftScaleRotate(shift_limit=0.08, scale_limit=0.12, rotate_limit=15, p=0.5),
    A.RandomBrightnessContrast(brightness_limit=0.25, contrast_limit=0.25, p=0.5),
    A.GaussianBlur(blur_limit=(3, 5), p=0.2),
    A.GridDistortion(num_steps=5, distort_limit=0.15, p=0.2),
    A.CLAHE(clip_limit=2.0, p=0.3),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
], additional_targets={'mask': 'mask'})

aug_val = A.Compose([
    A.Resize(IMG_H, IMG_W),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
], additional_targets={'mask': 'mask'})

#  10. HELPER FUNCTIONS
def polygon_to_mask(fname, h, w):
    mask = np.zeros((h, w), dtype=np.float32)
    if fname not in fname_to_anns:
        return mask[..., np.newaxis]
    for ann in fname_to_anns[fname]:
        sx = w / ann['orig_w']
        sy = h / ann['orig_h']
        for seg in ann['segmentation']:
            pts = np.array(seg, dtype=np.float32).reshape(-1, 2)
            pts[:, 0] *= sx
            pts[:, 1] *= sy
            cv2.fillPoly(mask, [pts.astype(np.int32)], 1.0)
    return mask[..., np.newaxis]

def get_bbox(fname):
    if fname not in fname_to_anns:
        return np.array([0., 0., 0., 0.], dtype=np.float32)
    ann      = fname_to_anns[fname][0]
    x, y, w, h = ann['bbox']
    ow, oh   = ann['orig_w'], ann['orig_h']
    return np.array([(x+w/2)/ow, (y+h/2)/oh, w/ow, h/oh], dtype=np.float32)

#  11. CLASS WEIGHTS
train_labels_list = [d['combined_label'] for d in train_data]
unique_labels     = np.unique(train_labels_list)
cw                = compute_class_weight('balanced', classes=unique_labels, y=train_labels_list)
class_weight_dict = dict(zip(unique_labels, cw))
print("Sample weights computed.")

#  12. TF DATA PIPELINE
def process_data(path, label, fname):
    def _process(path_b, label_b, fname_b):
        path_str  = path_b.decode('utf-8')
        fname_str = fname_b.decode('utf-8')
        img = cv2.imread(path_str)
        if img is None:
            img = np.zeros((IMG_H, IMG_W, 3), dtype=np.uint8)
        else:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, (IMG_W, IMG_H))
        lbl = np.float32(label_b)
        box = get_bbox(fname_str)
        msk = polygon_to_mask(fname_str, IMG_H, IMG_W)
        return img, lbl, box, msk

    img, lbl, box, msk = tf.numpy_function(
        _process, [path, label, fname],
        [tf.uint8, tf.float32, tf.float32, tf.float32])
    img.set_shape([IMG_H, IMG_W, 3])
    lbl.set_shape([])
    box.set_shape([4])
    msk.set_shape([IMG_H, IMG_W, 1])
    return img, lbl, box, msk

def augment_data(img, lbl, box, msk, weight, augment):
    def _aug(img_np, msk_np):
        msk_2d  = msk_np[:, :, 0]
        tfm     = aug_train(image=img_np, mask=msk_2d) if augment \
                  else aug_val(image=img_np, mask=msk_2d)
        aug_img = tfm['image'].astype(np.float32)
        aug_msk = tfm['mask'].astype(np.float32)[..., np.newaxis]
        return aug_img, aug_msk

    img_aug, msk_aug = tf.numpy_function(_aug, [img, msk], [tf.float32, tf.float32])
    img_aug.set_shape([IMG_H, IMG_W, 3])
    msk_aug.set_shape([IMG_H, IMG_W, 1])

    targets        = (lbl, msk_aug, box)
    sample_weights = (
        tf.cast(weight, tf.float32),
        tf.constant(1.0, dtype=tf.float32),
        tf.constant(1.0, dtype=tf.float32),
    )
    return img_aug, targets, sample_weights

def build_ds(data_list, augment=False, shuffle=False):
    paths   = [d['path']  for d in data_list]
    labels  = [d['label'] for d in data_list]
    fnames  = [d['fname'] for d in data_list]
    weights = [class_weight_dict.get(d['combined_label'], 1.0) for d in data_list]

    ds = tf.data.Dataset.from_tensor_slices((paths, labels, fnames, weights))
    if shuffle:
        ds = ds.shuffle(len(data_list), seed=SEED)
    ds = ds.map(lambda p, l, f, w: (*process_data(p, l, f), w),
                num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.cache()
    ds = ds.map(lambda img, lbl, box, msk, w: augment_data(img, lbl, box, msk, w, augment),
                num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds

print("Building datasets...")
train_ds = build_ds(train_data, augment=True,  shuffle=True)
val_ds   = build_ds(val_data,   augment=False, shuffle=False)
test_ds  = build_ds(test_data,  augment=False, shuffle=False)
print("Datasets ready")

#  13. LOSSES
def focal_loss(gamma=2.0, alpha=0.35):
    def loss_fn(y_true, y_pred):
        y_true  = tf.cast(y_true, tf.float32)
        y_pred  = tf.clip_by_value(y_pred, 1e-7, 1.0 - 1e-7)
        bce     = -y_true * tf.math.log(y_pred) - (1-y_true) * tf.math.log(1-y_pred)
        p_t     = y_true * y_pred + (1-y_true) * (1-y_pred)
        alpha_t = y_true * alpha  + (1-y_true) * (1-alpha)
        return tf.reduce_mean(alpha_t * tf.pow(1.0 - p_t, gamma) * bce)
    return loss_fn

def dice_bce_loss(smooth=1e-6):
    def loss_fn(y_true, y_pred):
        y_true = tf.cast(tf.reshape(y_true, [tf.shape(y_true)[0], -1]), tf.float32)
        y_pred = tf.cast(tf.reshape(y_pred, [tf.shape(y_pred)[0], -1]), tf.float32)
        y_pred = tf.clip_by_value(y_pred, 1e-7, 1.0 - 1e-7)
        intersection = tf.reduce_sum(y_true * y_pred, axis=1)
        union        = tf.reduce_sum(y_true, axis=1) + tf.reduce_sum(y_pred, axis=1)
        dice         = 1.0 - (2.0 * intersection + smooth) / (union + smooth)
        bce          = -tf.reduce_mean(
            y_true * tf.math.log(y_pred) + (1 - y_true) * tf.math.log(1 - y_pred), axis=1)
        return tf.reduce_mean(0.5 * dice + 0.5 * bce)
    return loss_fn

def seg_iou_metric(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.cast(y_pred > SEG_THRESHOLD, tf.float32)
    intersection = tf.reduce_sum(y_true * y_pred)
    union        = tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) - intersection
    return (intersection + 1e-6) / (union + 1e-6)

def seg_dice_metric(y_true, y_pred):
    y_true = tf.cast(y_true, tf.float32)
    y_pred = tf.cast(y_pred > SEG_THRESHOLD, tf.float32)
    intersection = 2.0 * tf.reduce_sum(y_true * y_pred)
    denom        = tf.reduce_sum(y_true) + tf.reduce_sum(y_pred)
    return (intersection + 1e-6) / (denom + 1e-6)

# ─────────────────────────── 14. MODEL ───────────────────────────────────────
def build_fracturenet(freeze=True):
    inputs   = keras.Input(shape=(IMG_H, IMG_W, 3), name='input')
    backbone = DenseNet121(include_top=False, weights='imagenet', input_tensor=inputs)
    backbone.trainable = not freeze
    feat = backbone.output
    print(f"Backbone: DenseNet121 → feature shape: {feat.shape}")
    reg  = regularizers.l2(L2_REG)

    # Head 1: Classification
    cls = layers.GlobalAveragePooling2D()(feat)
    cls = layers.Dense(512, activation='relu', kernel_regularizer=reg)(cls)
    cls = layers.BatchNormalization()(cls)
    cls = layers.Dropout(0.55)(cls)
    cls = layers.Dense(128, activation='relu', kernel_regularizer=reg)(cls)
    cls = layers.Dropout(0.4)(cls)
    cls_out = layers.Dense(1, activation='sigmoid', dtype='float32', name='cls_out')(cls)

    # Head 2: Segmentation — 5× upsample 7→224
    seg = layers.Conv2DTranspose(512, 3, strides=2, padding='same')(feat)
    seg = layers.BatchNormalization()(seg); seg = layers.Activation('relu')(seg)
    seg = layers.Conv2DTranspose(256, 3, strides=2, padding='same')(seg)
    seg = layers.BatchNormalization()(seg); seg = layers.Activation('relu')(seg)
    seg = layers.Conv2DTranspose(128, 3, strides=2, padding='same')(seg)
    seg = layers.BatchNormalization()(seg); seg = layers.Activation('relu')(seg)
    seg = layers.Conv2DTranspose(64,  3, strides=2, padding='same')(seg)
    seg = layers.BatchNormalization()(seg); seg = layers.Activation('relu')(seg)
    seg = layers.Conv2DTranspose(32,  3, strides=2, padding='same')(seg)
    seg = layers.BatchNormalization()(seg); seg = layers.Activation('relu')(seg)
    seg = layers.Conv2D(16, 3, padding='same', activation='relu')(seg)
    seg = layers.Conv2D(8,  3, padding='same', activation='relu')(seg)
    seg_out = layers.Conv2D(1, 1, activation='sigmoid', dtype='float32', name='seg_out')(seg)

    # Head 3: Localization
    loc = layers.GlobalAveragePooling2D()(feat)
    loc = layers.Dense(256, activation='relu', kernel_regularizer=reg)(loc)
    loc = layers.BatchNormalization()(loc)
    loc = layers.Dropout(0.3)(loc)
    loc = layers.Dense(64, activation='relu', kernel_regularizer=reg)(loc)
    loc_out = layers.Dense(4, activation='sigmoid', dtype='float32', name='loc_out')(loc)

    return Model(inputs, [cls_out, seg_out, loc_out],
                 name='FractureNet_DenseNet121'), backbone

def compile_model(model, lr):
    model.compile(
        optimizer=keras.optimizers.Adam(lr),
        loss={
            'cls_out': focal_loss(gamma=2.0, alpha=0.35),
            'seg_out': dice_bce_loss(),
            'loc_out': 'mse',
        },
        loss_weights={'cls_out': 4.0, 'seg_out': 2.0, 'loc_out': 0.5},
        metrics={
            'cls_out': [keras.metrics.BinaryAccuracy(name='acc'),
                        keras.metrics.AUC(name='auc')],
            'seg_out': [seg_iou_metric, seg_dice_metric],
            'loc_out': ['mae'],
        }
    )

print("Building FractureNet...")
model, backbone = build_fracturenet(freeze=True)
model.summary(line_length=100)

#  15. CALLBACKS
ckpt_path = '/content/best_fracturenet.keras'

def get_callbacks(patience_es, patience_lr):
    return [
        ModelCheckpoint(ckpt_path, monitor='val_cls_out_auc',
                        mode='max', save_best_only=True, verbose=1),
        EarlyStopping(monitor='val_cls_out_auc', patience=patience_es,
                      restore_best_weights=True, mode='max', verbose=1),
        ReduceLROnPlateau(monitor='val_loss', patience=patience_lr,
                          factor=0.5, min_lr=1e-8, verbose=1),
    ]

#  16. PHASE 1
print(f"PHASE 1 — Frozen backbone | LR={LR_PHASE1} | Epochs 1-{EPOCHS//2}")
compile_model(model, LR_PHASE1)
history1 = model.fit(train_ds, validation_data=val_ds,
                      epochs=EPOCHS//2, callbacks=get_callbacks(4, 2), verbose=1)

#  17. PHASE 2
FREEZE_N = 300
print(f"PHASE 2 — Fine-tune (freeze first {FREEZE_N} layers) | LR={LR_PHASE2}")
backbone.trainable = True
for layer in backbone.layers[:FREEZE_N]:
    layer.trainable = False
compile_model(model, LR_PHASE2)
history2 = model.fit(train_ds, validation_data=val_ds,
                      epochs=EPOCHS//2, callbacks=get_callbacks(5, 3), verbose=1)

#  18. TRAINING HISTORY
def merge_hist(h1, h2):
    return {k: h1.history[k] + h2.history[k] for k in h1.history}

H        = merge_hist(history1, history2)
n_ep     = len(H['loss'])
ep_range = range(1, n_ep + 1)

metrics_plot = [
    ('loss',                       'val_loss',                       'Total Loss',    '#E74C3C'),
    ('cls_out_acc',                'val_cls_out_acc',                'CLS Accuracy',  '#3498DB'),
    ('cls_out_auc',                'val_cls_out_auc',                'CLS AUC',       '#9B59B6'),
    ('seg_out_seg_iou_metric',     'val_seg_out_seg_iou_metric',     'SEG IoU',       '#27AE60'),
    ('seg_out_seg_dice_metric',    'val_seg_out_seg_dice_metric',    'SEG Dice',      '#1ABC9C'),
    ('loc_out_mae',                'val_loc_out_mae',                'LOC MAE',       '#F39C12'),
]

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle(f'FractureNet — Training History ({n_ep} Epochs)',
              fontsize=16, fontweight='bold')
axes = axes.flatten()

for idx, (tk, vk, title, color) in enumerate(metrics_plot):
    ax = axes[idx]
    if tk not in H:
        ax.set_visible(False); continue
    ax.plot(ep_range, H[tk], label='Train', color=color, lw=2.5, marker='o', ms=3)
    ax.plot(ep_range, H[vk], label='Val',   color=color, lw=2.5,
            linestyle='--', marker='s', ms=3, alpha=0.7)
    ax.axvline(EPOCHS//2 + 0.5, color='gray', ls=':', lw=1.5, label='Phase 1→2')
    ax.set_title(title, fontweight='bold', fontsize=12)
    ax.set_xlabel('Epoch')
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)
    ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.savefig('/content/01_training_history.png', dpi=150, bbox_inches='tight')
plt.show()

#  19. TEST EVALUATION
print("Test Set Evaluation")
model.evaluate(test_ds, verbose=1)

y_true, y_prob, y_pred       = [], [], []
all_true_masks, all_pred_masks = [], []

for img_b, lbl_b, _ in test_ds:
    cp, sp, _ = model.predict(img_b, verbose=0)
    cls_true  = lbl_b[0].numpy().astype(int)
    seg_true  = lbl_b[1].numpy()   # targets=(lbl, msk, box) → index 1

    y_true.extend(cls_true.tolist())
    y_prob.extend(cp.flatten().tolist())
    y_pred.extend((cp.flatten() > CLS_THRESHOLD).astype(int).tolist())
    all_true_masks.append(seg_true)
    all_pred_masks.append(sp)

print(f"\nClassification Threshold: {CLS_THRESHOLD}")
print(classification_report(y_true, y_pred,
                             target_names=['Non-Fractured', 'Fractured']))
try:
    print(f"AUC-ROC: {roc_auc_score(y_true, y_prob):.4f}")
except Exception as e:
    print(f"AUC: {e}")

# Segmentation metrics
all_true_masks = np.concatenate(all_true_masks, axis=0)
all_pred_masks = np.concatenate(all_pred_masks, axis=0)

frac_idx = [i for i, l in enumerate(y_true) if l == 1]
if frac_idx:
    gt        = all_true_masks[frac_idx]
    pr        = (all_pred_masks[frac_idx] > SEG_THRESHOLD).astype(np.float32)
    intersection = np.sum(gt * pr)
    union        = np.sum(gt) + np.sum(pr) - intersection
    mean_iou  = (intersection + 1e-6) / (union + 1e-6)
    mean_dice = (2*intersection + 1e-6) / (np.sum(gt) + np.sum(pr) + 1e-6)
    print(f"\nSegmentation (Fractured only, n={len(frac_idx)}):")
    print(f"  Mean IoU   : {mean_iou:.4f}")
    print(f"  Mean Dice  : {mean_dice:.4f}")

# Confusion matrix
cm = confusion_matrix(y_true, y_pred)
fig, ax = plt.subplots(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Non-Fractured', 'Fractured'],
            yticklabels=['Non-Fractured', 'Fractured'],
            ax=ax, linewidths=0.5, cbar_kws={'shrink': 0.8})
ax.set_title('Confusion Matrix — Test Set', fontweight='bold', fontsize=14, pad=15)
ax.set_xlabel('Predicted'); ax.set_ylabel('True')
plt.tight_layout()
plt.savefig('/content/02_confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

#  20. SEGMENTATION VISUALIZATION
def denorm(img):
    return np.clip(img * np.array([0.229,0.224,0.225]) +
                   np.array([0.485,0.456,0.406]), 0, 1)

for img_b, lbl_b, _ in test_ds.take(1):
    cp, sp, lp = model.predict(img_b, verbose=0)
    cls_true   = lbl_b[0].numpy()
    seg_true   = lbl_b[1].numpy()   # index 1 = mask
    break

frac_show_idx = [i for i in range(img_b.shape[0]) if cls_true[i] > 0.5][:6]
n_show        = len(frac_show_idx)

if n_show > 0:
    fig, axes = plt.subplots(n_show, 4, figsize=(18, 4.5 * n_show))
    if n_show == 1:
        axes = axes[np.newaxis, :]
    fig.suptitle('Segmentation Results — Fractured Cases',
                  fontsize=14, fontweight='bold', y=1.01)
    for c, t in enumerate(['Original Image', 'Ground Truth Mask', 'Predicted Mask', 'Overlay']):
        axes[0, c].set_title(t, fontweight='bold', fontsize=11)

    for row, i in enumerate(frac_show_idx):
        vis      = denorm(img_b[i].numpy())
        gt_mask  = seg_true[i, :, :, 0]
        pr_mask  = sp[i, :, :, 0]
        pr_bin   = (pr_mask > SEG_THRESHOLD).astype(np.float32)
        prob_cls = float(cp[i][0])

        axes[row, 0].imshow(vis)
        axes[row, 0].set_ylabel(f'P(frac)={prob_cls:.1%}', fontsize=9)
        axes[row, 0].axis('off')

        axes[row, 1].imshow(vis)
        if gt_mask.sum() > 0:
            axes[row, 1].imshow(gt_mask, alpha=0.6, cmap='Greens', vmin=0, vmax=1)
        axes[row, 1].axis('off')

        axes[row, 2].imshow(pr_mask, cmap='hot', vmin=0, vmax=1)
        axes[row, 2].axis('off')

        axes[row, 3].imshow(vis)
        if pr_bin.sum() > 0:
            axes[row, 3].imshow(pr_bin, alpha=0.55, cmap='Reds', vmin=0, vmax=1)
        if gt_mask.sum() > 0:
            axes[row, 3].contour(gt_mask, levels=[0.5], colors=['lime'], linewidths=2)
        axes[row, 3].axis('off')

    plt.tight_layout()
    plt.savefig('/content/03_segmentation_results.png', dpi=150, bbox_inches='tight')
    plt.show()
    print("Saved: /content/03_segmentation_results.png")
else:
    print("No fractured cases in this batch for visualization.")

#  21. FINAL SUMMARY
best_auc = max(H.get('val_cls_out_auc', [0]))
best_ep  = np.argmax(H.get('val_cls_out_auc', [0])) + 1

print("TRAINING COMPLETE")
print(f"  Model       : FractureNet (DenseNet121)")
print(f"  Epochs run  : {n_ep}  (Phase1={n_ep//2} + Phase2={n_ep//2})")
print(f"  Best Val AUC: {best_auc:.4f}  (epoch {best_ep})")
if frac_idx:
    print(f"  Seg IoU     : {mean_iou:.4f}")
    print(f"  Seg Dice    : {mean_dice:.4f}")
print("\n  Outputs:")
print("    /content/best_fracturenet.keras")
print("    /content/01_training_history.png")
print("    /content/02_confusion_matrix.png")
print("    /content/03_segmentation_results.png")

