# -*- coding: utf-8 -*-
"""DenseNet121(1) (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2AtNQgaBGPatOQEkZYGJIawfHnOWuu_
"""

# ╔══════════════════════════════════════════════════════════════════╗
# ║  BONE FRACTURE DETECTION — FractureNet Multi-Task (TensorFlow)  ║
# ║  Classification + Localization + Segmentation                   ║
# ╚══════════════════════════════════════════════════════════════════╝

# 0. INSTALL

import subprocess
subprocess.run(['pip', 'install', '-q', 'albumentations'], check=False)

# 1. IMPORTS
import os, json, zipfile, random, warnings, glob
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from PIL import Image
from tqdm import tqdm
warnings.filterwarnings('ignore')

import cv2
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, Model
from tensorflow.keras.applications import EfficientNetB0, EfficientNetB3, EfficientNetB4, ResNet50V2, DenseNet121
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau, ModelCheckpoint
from sklearn.model_selection import train_test_split
from sklearn.utils import resample
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import seaborn as sns
import albumentations as A

print(f" TensorFlow : {tf.__version__}")
print(f" GPU        : {tf.config.list_physical_devices('GPU')}")

# 2. CONFIGURATION
IMG_SIZE   = (224, 224)
BATCH_SIZE = 32
EPOCHS     = 20
SEED       = 42
LR_PHASE1  = 1e-3
LR_PHASE2  = 5e-5

# 'DenseNet121'
MODEL_CHOICE = 'DenseNet121'

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)
os.environ['PYTHONHASHSEED'] = str(SEED)

IMG_H, IMG_W = IMG_SIZE

tf.keras.mixed_precision.set_global_policy('mixed_float16')
print(f" Mixed Precision: {tf.keras.mixed_precision.global_policy().name}")
print(f" Model Choice   : {MODEL_CHOICE}")

def find_zip_file():
    candidates = [
        '/content/archive__32_.zip',
        '/content/drive/MyDrive/archive__32_.zip',
        '/content/drive/My Drive/archive__32_.zip',
    ]
    drive_search = glob.glob('/content/drive/**/*archive*32*.zip', recursive=True)
    drive_search += glob.glob('/content/drive/**/*.zip', recursive=True)
    candidates += drive_search

    for path in candidates:
        if os.path.exists(path):
            print(f"I found the file ZIP: {path}")
            return path
    return None

try:
    from google.colab import drive
    if not os.path.exists('/content/drive'):
        print("Installation in progress Google Drive...")
        drive.mount('/content/drive')
    else:
        print(" Google Drive Pre-assembled")
except Exception as e:
    print(f"  Drive Not available: {e}")

ZIP_PATH = find_zip_file()

if ZIP_PATH is None:
    print("\n  The file was not found automatically.")
    print("Upload the file now (archive__32_.zip)...")
    try:
        from google.colab import files
        uploaded = files.upload()
        for fname in uploaded:
            dest = f'/content/{fname}'
            with open(dest, 'wb') as f:
                f.write(uploaded[fname])
            ZIP_PATH = dest
            print(f"Uploaded: {dest}")
            break
    except Exception as e:
        raise FileNotFoundError(
            f" The file was not found.\n"
            f"Solution: Manually upload the file to /content/ and press Run again. \n{e}"
        )

print(f"\npath ZIP: {ZIP_PATH}")


# 4. EXTRACT ZIP
print("\n Extracting dataset...")

EXTRACT_ROOT = '/content/extracted_dataset'
os.makedirs(EXTRACT_ROOT, exist_ok=True)

with zipfile.ZipFile(ZIP_PATH, 'r') as z:
    z.extractall(EXTRACT_ROOT)

print(" Extraction complete")

DATASET_DIR = None
for root, dirs, _ in os.walk(EXTRACT_ROOT):
    if 'FracAtlas' in dirs:
        DATASET_DIR = os.path.join(root, 'FracAtlas')
        break
    if os.path.basename(root) == 'FracAtlas':
        DATASET_DIR = root
        break

if DATASET_DIR is None:
    for root, dirs, _ in os.walk(EXTRACT_ROOT):
        if 'images' in dirs:
            DATASET_DIR = root
            break

if DATASET_DIR is None:
    raise FileNotFoundError(f"The FracAtlas folder was not found inside theZIP.\n"
                             f"Extracted volumes: {os.listdir(EXTRACT_ROOT)}")

print(f" Dataset path: {DATASET_DIR}")

FRAC_DIR    = os.path.join(DATASET_DIR, 'images', 'Fractured')
NONFRAC_DIR = os.path.join(DATASET_DIR, 'images', 'Non_fractured')
COCO_PATH   = os.path.join(DATASET_DIR, 'Annotations', 'COCO JSON', 'COCO_fracture_masks.json')

for p in [FRAC_DIR, NONFRAC_DIR, COCO_PATH]:
    if not os.path.exists(p):
        raise FileNotFoundError(f" Lost Path: {p}")
print(" All dataset paths verified")

# 5. NORMALIZE EXTENSIONS & IMAGE SIZES
def normalize_images(folder, target_ext='.jpg', target_size=IMG_SIZE):
    converted = 0
    for fname in os.listdir(folder):
        fpath = os.path.join(folder, fname)
        ext = os.path.splitext(fname)[1].lower()
        if ext not in ['.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp']:
            continue
        try:
            img = Image.open(fpath).convert('RGB')
            if ext != target_ext:
                new_path = os.path.splitext(fpath)[0] + target_ext
                img.save(new_path, 'JPEG', quality=95)
                os.remove(fpath)
                converted += 1
        except Exception as e:
            print(f"  Skipping {fname}: {e}")
    print(f"  Converted {converted} files in {os.path.basename(folder)}")

print("\n Normalizing image extensions...")
normalize_images(FRAC_DIR)
normalize_images(NONFRAC_DIR)

# 6. LOAD COCO ANNOTATIONS
with open(COCO_PATH, 'r') as f:
    coco_data = json.load(f)

id_to_img     = {img['id']: img for img in coco_data['images']}
fname_to_anns = {}
for ann in coco_data['annotations']:
    img_info = id_to_img[ann['image_id']]
    fname    = img_info['file_name']
    if fname not in fname_to_anns:
        fname_to_anns[fname] = []
    fname_to_anns[fname].append({
        'bbox'        : ann['bbox'],
        'segmentation': ann['segmentation'],
        'orig_w'      : img_info['width'],
        'orig_h'      : img_info['height'],
    })

print(f"\n Loaded {len(coco_data['annotations'])} annotations "
      f"for {len(fname_to_anns)} fractured images")

# 7. DATA EXPLORATION & VISUALIZATION
VALID_EXTS    = ('.jpg', '.jpeg', '.png')
frac_files    = [f for f in os.listdir(FRAC_DIR)    if f.lower().endswith(VALID_EXTS)]
nonfrac_files = [f for f in os.listdir(NONFRAC_DIR) if f.lower().endswith(VALID_EXTS)]

n_frac    = len(frac_files)
n_nonfrac = len(nonfrac_files)
total     = n_frac + n_nonfrac

print(f"\n{'='*50}")
print(f"  Fractured    : {n_frac:>5}  ({100*n_frac/total:.1f}%)")
print(f"  Non-Fractured: {n_nonfrac:>5}  ({100*n_nonfrac/total:.1f}%)")
print(f"  Total        : {total:>5}")
print(f"  Imbalance    : 1:{n_nonfrac//max(n_frac,1)}")
print(f"{'='*50}")

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle(' FracAtlas — Dataset Analysis', fontsize=16, fontweight='bold', y=0.98)

# Bar chart
ax = axes[0, 0]
bars = ax.bar(['Fractured', 'Non-Fractured'], [n_frac, n_nonfrac],
              color=['#E74C3C', '#2ECC71'], edgecolor='white', linewidth=1.5, width=0.5)
for bar, val in zip(bars, [n_frac, n_nonfrac]):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 40,
            f'{val}\n({100*val/total:.1f}%)', ha='center', fontweight='bold', fontsize=11)
ax.set_title('Class Distribution', fontweight='bold')
ax.set_ylabel('Number of Images')
ax.set_ylim(0, max(n_frac, n_nonfrac) * 1.25)
ax.spines[['top', 'right']].set_visible(False)

# Pie chart
ax = axes[0, 1]
_, _, autotexts = ax.pie(
    [n_frac, n_nonfrac],
    labels=['Fractured', 'Non-Fractured'],
    autopct='%1.1f%%',
    colors=['#E74C3C', '#2ECC71'],
    startangle=140,
    wedgeprops={'edgecolor': 'white', 'linewidth': 2}
)
for at in autotexts:
    at.set_fontweight('bold')
ax.set_title('Class Ratio', fontweight='bold')

# Image width distribution
ax = axes[0, 2]
widths = []
for f in random.sample(frac_files,    min(50, len(frac_files))):
    try: widths.append(Image.open(os.path.join(FRAC_DIR, f)).size[0])
    except: pass
for f in random.sample(nonfrac_files, min(50, len(nonfrac_files))):
    try: widths.append(Image.open(os.path.join(NONFRAC_DIR, f)).size[0])
    except: pass
ax.hist(widths, bins=25, color='steelblue', edgecolor='white', alpha=0.85)
if widths:
    ax.axvline(np.mean(widths), color='red', linestyle='--',
               label=f'Mean: {np.mean(widths):.0f}px')
ax.set_title('Image Width Distribution (sample)', fontweight='bold')
ax.set_xlabel('Width (pixels)')
ax.set_ylabel('Count')
ax.legend()
ax.spines[['top', 'right']].set_visible(False)

# Sample fractured images with bbox
sample_frac = random.sample(frac_files, min(3, len(frac_files)))
for i, fname in enumerate(sample_frac):
    img = np.array(Image.open(os.path.join(FRAC_DIR, fname)).convert('RGB'))
    axes[1, i].imshow(img)
    axes[1, i].set_title('🔴 Fractured', fontweight='bold', color='#E74C3C')
    axes[1, i].axis('off')
    if fname in fname_to_anns:
        ann = fname_to_anns[fname][0]
        x, y, w, h = ann['bbox']
        sx = img.shape[1] / ann['orig_w']
        sy = img.shape[0] / ann['orig_h']
        rect = patches.Rectangle((x*sx, y*sy), w*sx, h*sy,
                                   linewidth=2, edgecolor='yellow', facecolor='none')
        axes[1, i].add_patch(rect)
        axes[1, i].set_title('🔴 Fractured (bbox)', fontweight='bold', color='#E74C3C')

plt.tight_layout()
plt.savefig('/content/01_data_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Saved: /content/01_data_analysis.png")

# 8. BUILD DATASET LIST
import csv
fname_to_bp = {}
CSV_PATH = os.path.join(DATASET_DIR, 'dataset.csv')
if os.path.exists(CSV_PATH):
    with open(CSV_PATH, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get('mixed', '0') == '1':
                bp = 'mixed'
            else:
                bps = [b for b in ['hand', 'leg', 'hip', 'shoulder'] if row.get(b, '0') == '1']
                bp = bps[0] if bps else 'unknown'
            fname_to_bp[row['image_id']] = bp
else:
    print("The dataset.csv file was not found; it will be assumed that all parts 'unknown'")

all_data = []
for f in frac_files:
    bp = fname_to_bp.get(f, 'unknown')
    all_data.append({'path': os.path.join(FRAC_DIR, f), 'label': 1, 'fname': f, 'bp': bp, 'combined_label': f"1_{bp}"})
for f in nonfrac_files:
    bp = fname_to_bp.get(f, 'unknown')
    all_data.append({'path': os.path.join(NONFRAC_DIR, f), 'label': 0, 'fname': f, 'bp': bp, 'combined_label': f"0_{bp}"})
random.shuffle(all_data)

# 9. CLASS DISTRIBUTION
frac_data    = [d for d in all_data if d['label'] == 1]
nonfrac_data = [d for d in all_data if d['label'] == 0]
print(f"\n Fractured: {len(frac_data)} | Non-Fractured: {len(nonfrac_data)}")
print(f"   (Sample weights will be used to address imbalances in fractures and body parts)")


# 10. TRAIN / VAL / TEST SPLIT  70 / 15 / 15
labels_all = [d['combined_label'] for d in all_data]
from collections import Counter
counts = Counter(labels_all)
safe_labels_all = [l if counts[l] >= 4 else f"{l.split('_')[0]}_rare" for l in labels_all]

train_data, temp_data = train_test_split(all_data, test_size=0.30,
                                          stratify=safe_labels_all, random_state=SEED)

labels_temp = [d['combined_label'] for d in temp_data]
counts_temp = Counter(labels_temp)
safe_labels_temp = [l if counts_temp[l] >= 2 else f"{l.split('_')[0]}_rare" for l in labels_temp]

val_data, test_data = train_test_split(temp_data, test_size=0.50,
                                        stratify=safe_labels_temp, random_state=SEED)
print(f"\n Train:{len(train_data)} | Val:{len(val_data)} | Test:{len(test_data)}")

# 11. DATA AUGMENTATION
aug_train = A.Compose([
    A.Resize(IMG_H, IMG_W),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.3),
    A.RandomRotate90(p=0.3),
    A.ShiftScaleRotate(shift_limit=0.08, scale_limit=0.12, rotate_limit=15, p=0.5),
    A.RandomBrightnessContrast(brightness_limit=0.25, contrast_limit=0.25, p=0.5),
    A.GaussianBlur(blur_limit=(3, 5), p=0.2),
    A.GridDistortion(num_steps=5, distort_limit=0.15, p=0.2),
    A.CLAHE(clip_limit=2.0, p=0.3),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
])
aug_val = A.Compose([
    A.Resize(IMG_H, IMG_W),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
])

# Augmentation preview
sample_path = os.path.join(FRAC_DIR, frac_files[0])
sample_img  = cv2.cvtColor(cv2.imread(sample_path), cv2.COLOR_BGR2RGB)
fig, axes   = plt.subplots(1, 6, figsize=(20, 4))
fig.suptitle(' Data Augmentation Examples', fontweight='bold', fontsize=14)
axes[0].imshow(cv2.resize(sample_img, IMG_SIZE))
axes[0].set_title('Original', fontweight='bold'); axes[0].axis('off')
for i in range(1, 6):
    aug_img = aug_train(image=sample_img)['image']
    vis = np.clip(aug_img * np.array([0.229,0.224,0.225]) + np.array([0.485,0.456,0.406]), 0, 1)
    axes[i].imshow(vis)
    axes[i].set_title(f'Aug #{i}', fontweight='bold'); axes[i].axis('off')
plt.tight_layout()
plt.savefig('/content/02_augmentation.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Saved: /content/02_augmentation.png")

# 12. HELPER FUNCTIONS
def polygon_to_mask(fname, h, w):
    mask = np.zeros((h, w), dtype=np.float32)
    if fname not in fname_to_anns:
        return mask[..., np.newaxis]
    for ann in fname_to_anns[fname]:
        sx = w / ann['orig_w']
        sy = h / ann['orig_h']
        for seg in ann['segmentation']:
            pts = np.array(seg, dtype=np.float32).reshape(-1, 2)
            pts[:, 0] *= sx
            pts[:, 1] *= sy
            cv2.fillPoly(mask, [pts.astype(np.int32)], 1.0)
    return mask[..., np.newaxis]

def get_bbox(fname):
    if fname not in fname_to_anns:
        return np.array([0., 0., 0., 0.], dtype=np.float32)
    ann = fname_to_anns[fname][0]
    x, y, w, h = ann['bbox']
    ow, oh = ann['orig_w'], ann['orig_h']
    return np.array([(x+w/2)/ow, (y+h/2)/oh, w/ow, h/oh], dtype=np.float32)

# 13. TF DATA PIPELINE (NATIVE & OPTIMIZED)
from sklearn.utils.class_weight import compute_class_weight
train_labels_list = [d['combined_label'] for d in train_data]
unique_labels = np.unique(train_labels_list)
cw = compute_class_weight('balanced', classes=unique_labels, y=train_labels_list)
class_weight_dict = dict(zip(unique_labels, cw))

print("\n  Sample Weights (To compensate for the lack of images of the pelvis and shoulder):")
for k, v in class_weight_dict.items():
    print(f"   - {k}: {v:.3f}")

def process_data(path, label, fname):
    def _process(path_b, label_b, fname_b):
        path_str = path_b.decode('utf-8')
        fname_str = fname_b.decode('utf-8')

        img = cv2.imread(path_str)
        if img is None:
            img = np.zeros((IMG_H, IMG_W, 3), dtype=np.uint8)
        else:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = cv2.resize(img, (IMG_W, IMG_H))

        lbl = np.float32(label_b)
        box = get_bbox(fname_str)
        msk = polygon_to_mask(fname_str, IMG_H, IMG_W)
        return img, lbl, box, msk

    img, lbl, box, msk = tf.numpy_function(
        _process,
        [path, label, fname],
        [tf.uint8, tf.float32, tf.float32, tf.float32]
    )
    img.set_shape([IMG_H, IMG_W, 3])
    lbl.set_shape([])
    box.set_shape([4])
    msk.set_shape([IMG_H, IMG_W, 1])
    return img, lbl, box, msk

def augment_data(img, lbl, box, msk, weight, augment):
    def _aug(img_np):
        if augment:
            tfm = aug_train(image=img_np)
        else:
            tfm = aug_val(image=img_np)
        return tfm['image'].astype(np.float32)

    img_aug = tf.numpy_function(_aug, [img], tf.float32)
    img_aug.set_shape([IMG_H, IMG_W, 3])

    targets = (lbl, box, msk)
    sample_weights = (
        tf.cast(weight, tf.float32),
        tf.constant(1.0, dtype=tf.float32),
        tf.ones((1, 1), dtype=tf.float32)
    )
    return img_aug, targets, sample_weights

def build_ds(data_list, augment=False, shuffle=False):
    paths   = [d['path'] for d in data_list]
    labels  = [d['label'] for d in data_list]
    fnames  = [d['fname'] for d in data_list]
    weights = [class_weight_dict[d['combined_label']] for d in data_list]

    ds = tf.data.Dataset.from_tensor_slices((paths, labels, fnames, weights))

    if shuffle:
        ds = ds.shuffle(len(data_list), seed=SEED)

    ds = ds.map(lambda p, l, f, w: (*process_data(p, l, f), w), num_parallel_calls=tf.data.AUTOTUNE)

    ds = ds.cache()

    ds = ds.map(lambda img, lbl, box, msk, w: augment_data(img, lbl, box, msk, w, augment), num_parallel_calls=tf.data.AUTOTUNE)

    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(tf.data.AUTOTUNE)
    return ds

print("\n Building NATIVE TF datasets...")
train_ds = build_ds(train_data, augment=True,  shuffle=True)
val_ds   = build_ds(val_data,   augment=False, shuffle=False)
test_ds  = build_ds(test_data,  augment=False, shuffle=False)
print(" Datasets ready")

# 14. MODEL
def build_fracturenet(freeze=True, model_choice='EfficientNetB0'):
    inputs   = keras.Input(shape=(IMG_H, IMG_W, 3), name='input')

    backbone_map = {
        'EfficientNetB0': EfficientNetB0,
        'EfficientNetB3': EfficientNetB3,
        'EfficientNetB4': EfficientNetB4,
        'ResNet50V2'    : ResNet50V2,
        'DenseNet121'   : DenseNet121,
    }
    if model_choice not in backbone_map:
        raise ValueError(f" Backbone Unsupported: {model_choice}. "
                         f"Options: {list(backbone_map.keys())}")

    BackboneClass = backbone_map[model_choice]
    backbone = BackboneClass(include_top=False, weights='imagenet', input_tensor=inputs)
    backbone.trainable = not freeze
    feat = backbone.output
    print(f" Backbone: {model_choice} → feature shape: {feat.shape}")

    # Head 1: Classification
    cls = layers.GlobalAveragePooling2D()(feat)
    cls = layers.Dense(512, activation='relu')(cls)
    cls = layers.BatchNormalization()(cls)
    cls = layers.Dropout(0.45)(cls)
    cls = layers.Dense(128, activation='relu')(cls)
    cls = layers.Dropout(0.3)(cls)
    cls_out = layers.Dense(1, activation='sigmoid', dtype='float32', name='cls_out')(cls)

    # Head 2: Localization
    loc = layers.GlobalAveragePooling2D()(feat)
    loc = layers.Dense(256, activation='relu')(loc)
    loc = layers.BatchNormalization()(loc)
    loc = layers.Dropout(0.3)(loc)
    loc = layers.Dense(64, activation='relu')(loc)
    loc_out = layers.Dense(4, activation='sigmoid', dtype='float32', name='loc_out')(loc)

    # Head 3: Segmentation (5× upsample 7→224)
    seg = layers.Conv2DTranspose(512, 3, strides=2, padding='same', activation='relu')(feat)
    seg = layers.BatchNormalization()(seg)
    seg = layers.Conv2DTranspose(256, 3, strides=2, padding='same', activation='relu')(seg)
    seg = layers.BatchNormalization()(seg)
    seg = layers.Conv2DTranspose(128, 3, strides=2, padding='same', activation='relu')(seg)
    seg = layers.BatchNormalization()(seg)
    seg = layers.Conv2DTranspose(64,  3, strides=2, padding='same', activation='relu')(seg)
    seg = layers.BatchNormalization()(seg)
    seg = layers.Conv2DTranspose(32,  3, strides=2, padding='same', activation='relu')(seg)
    seg = layers.Conv2D(16, 3, padding='same', activation='relu')(seg)
    seg_out = layers.Conv2D(1, 1, activation='sigmoid', dtype='float32', name='seg_out')(seg)

    return Model(inputs, [cls_out, loc_out, seg_out], name=f'FractureNet_{model_choice}'), backbone

def compile_model(model, lr):
    model.compile(
        optimizer=keras.optimizers.Adam(lr),
        loss={'cls_out': 'binary_crossentropy',
              'loc_out': 'mse',
              'seg_out': 'binary_crossentropy'},
        loss_weights={'cls_out': 2.0, 'loc_out': 0.5, 'seg_out': 1.0},
        metrics={'cls_out': [keras.metrics.BinaryAccuracy(name='acc'),
                             keras.metrics.AUC(name='auc')],
                 'loc_out': ['mae'],
                 'seg_out': [keras.metrics.BinaryAccuracy(name='acc'),
                             keras.metrics.MeanIoU(num_classes=2, name='iou')]}
    )

print(f"\n  Building FractureNet with {MODEL_CHOICE}...")
model, backbone = build_fracturenet(freeze=True, model_choice=MODEL_CHOICE)
model.summary(line_length=100)

# 15. CALLBACKS
ckpt_path = '/content/best_fracturenet.keras'

def get_callbacks(patience_es, patience_lr):
    return [
        ModelCheckpoint(ckpt_path, monitor='val_cls_out_auc',
                        mode='max', save_best_only=True, verbose=1),
        EarlyStopping(monitor='val_cls_out_auc', patience=patience_es,
                      restore_best_weights=True, mode='max', verbose=1),
        ReduceLROnPlateau(monitor='val_loss', patience=patience_lr,
                          factor=0.5, min_lr=1e-8, verbose=1),
    ]

# 17. PHASE 1: FROZEN BACKBONE — 10 epochs
print("\n" + "="*60)
print(f" PHASE 1 — {MODEL_CHOICE} frozen | LR=1e-3 | Epochs 1-{EPOCHS//2}")
print("="*60)
compile_model(model, LR_PHASE1)
history1 = model.fit(train_ds, validation_data=val_ds,
                      epochs=EPOCHS//2, callbacks=get_callbacks(4, 2), verbose=1)

# 18. PHASE 2: FINE-TUNE — 10 epochs
freeze_map = {
    'EfficientNetB0': 100,
    'EfficientNetB3': 130,
    'EfficientNetB4': 150,
    'ResNet50V2'    : 100,
    'DenseNet121'   : 300,
}
freeze_n = freeze_map.get(MODEL_CHOICE, 100)

print("\n" + "="*60)
print(f" PHASE 2 — Fine-tune (freeze first {freeze_n} layers) | LR={LR_PHASE2} | Epochs {EPOCHS//2+1}-{EPOCHS}")
print("="*60)
backbone.trainable = True
for layer in backbone.layers[:freeze_n]:
    layer.trainable = False
compile_model(model, LR_PHASE2)
history2 = model.fit(train_ds, validation_data=val_ds,
                      epochs=EPOCHS//2, callbacks=get_callbacks(5, 3), verbose=1)

# 19. PLOT TRAINING HISTORY
def merge_hist(h1, h2):
    return {k: h1.history[k] + h2.history[k] for k in h1.history}

H          = merge_hist(history1, history2)
n_ep       = len(H['loss'])
ep_range   = range(1, n_ep + 1)
phase_line = EPOCHS // 2

metrics_plot = [
    ('loss',          'val_loss',          'Total Loss',              '#E74C3C'),
    ('cls_out_acc',   'val_cls_out_acc',   'Classification Accuracy', '#3498DB'),
    ('cls_out_auc',   'val_cls_out_auc',   'Classification AUC',      '#9B59B6'),
    ('loc_out_mae',   'val_loc_out_mae',   'Localization MAE',         '#F39C12'),
    ('seg_out_acc',   'val_seg_out_acc',   'Segmentation Accuracy',   '#27AE60'),
    ('seg_out_iou',   'val_seg_out_iou',   'Segmentation IoU',         '#1ABC9C'),
]

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle(f' FractureNet ({MODEL_CHOICE}) — Training History ({n_ep} Epochs)',
              fontsize=16, fontweight='bold')
axes = axes.flatten()

for idx, (tk, vk, title, color) in enumerate(metrics_plot):
    ax = axes[idx]
    if tk not in H:
        ax.set_visible(False); continue
    ax.plot(ep_range, H[tk], label='Train', color=color, lw=2.5, marker='o', ms=3)
    ax.plot(ep_range, H[vk], label='Val',   color=color, lw=2.5,
            linestyle='--', marker='s', ms=3, alpha=0.7)
    ax.axvline(phase_line + 0.5, color='gray', ls=':', lw=1.5, label='Phase 1→2')
    ax.set_title(title, fontweight='bold', fontsize=12)
    ax.set_xlabel('Epoch')
    ax.legend(fontsize=9)
    ax.grid(True, alpha=0.3)
    ax.spines[['top', 'right']].set_visible(False)

plt.tight_layout()
plt.savefig('/content/03_training_history.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Saved: /content/03_training_history.png")

# 19. EVALUATE ON TEST SET

print("\n" + "="*60)
print(" Test Set Evaluation")
print("="*60)
test_results = model.evaluate(test_ds, verbose=1)
print("\n Test Metrics:")
for name, val in zip(model.metrics_names, test_results):
    print(f"  {name:<35}: {val:.4f}")

y_true, y_prob, y_pred = [], [], []
for img_b, lbl_b, _ in test_ds:
    cp, _, _ = model.predict(img_b, verbose=0)
    y_true.extend(lbl_b[0].numpy().astype(int).tolist())
    y_prob.extend(cp.flatten().tolist())
    y_pred.extend((cp.flatten() > 0.5).astype(int).tolist())

print("\n Classification Report:")
print(classification_report(y_true, y_pred,
                             target_names=['Non-Fractured', 'Fractured']))
try:
    print(f" AUC-ROC: {roc_auc_score(y_true, y_prob):.4f}")
except Exception as e:
    print(f"AUC: {e}")

cm = confusion_matrix(y_true, y_pred)
fig, ax = plt.subplots(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Non-Fractured', 'Fractured'],
            yticklabels=['Non-Fractured', 'Fractured'],
            ax=ax, linewidths=0.5, cbar_kws={'shrink': 0.8})
ax.set_title('Confusion Matrix — Test Set', fontweight='bold', fontsize=14, pad=15)
ax.set_xlabel('Predicted'); ax.set_ylabel('True')
plt.tight_layout()
plt.savefig('/content/04_confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Saved: /content/04_confusion_matrix.png")

# 20. PREDICTION VISUALIZATION
def denorm(img):
    return np.clip(img * np.array([0.229,0.224,0.225]) + np.array([0.485,0.456,0.406]), 0, 1)

for img_b, lbl_b, _ in test_ds.take(1):
    cp, lp, sp = model.predict(img_b, verbose=0)
    break

cls_true = lbl_b[0].numpy()
loc_true = lbl_b[1].numpy()
seg_true = lbl_b[2].numpy()
n_show   = min(5, img_b.shape[0])

fig, axes = plt.subplots(n_show, 5, figsize=(22, 4.5 * n_show))
fig.suptitle(' FractureNet — Classification | Localization | Segmentation',
              fontsize=13, fontweight='bold', y=1.01)

for col, title in enumerate(['Original', 'GT BBox', 'Pred BBox', 'GT Mask', 'Pred Mask']):
    axes[0, col].set_title(title, fontweight='bold', fontsize=11)

for i in range(n_show):
    vis          = denorm(img_b[i].numpy())
    is_true_frac = cls_true[i] > 0.5
    is_pred_frac = cp[i][0]   > 0.5
    prob         = float(cp[i][0])

    # Col 0: Original
    axes[i, 0].imshow(vis)
    axes[i, 0].set_title('🔴 Fractured' if is_true_frac else '🟢 Normal', fontsize=9)
    axes[i, 0].axis('off')

    # Col 1: GT bbox
    axes[i, 1].imshow(vis)
    if is_true_frac and loc_true[i].sum() > 0:
        xc, yc, bw, bh = loc_true[i]
        rect = patches.Rectangle(((xc-bw/2)*IMG_W, (yc-bh/2)*IMG_H),
                                   bw*IMG_W, bh*IMG_H, lw=2, edgecolor='lime', facecolor='none')
        axes[i, 1].add_patch(rect)
    axes[i, 1].axis('off')

    # Col 2: Pred bbox
    axes[i, 2].imshow(vis)
    if is_pred_frac:
        xc, yc, bw, bh = lp[i]
        rect = patches.Rectangle(((xc-bw/2)*IMG_W, (yc-bh/2)*IMG_H),
                                   bw*IMG_W, bh*IMG_H, lw=2, edgecolor='yellow', facecolor='none')
        axes[i, 2].add_patch(rect)
    axes[i, 2].set_title(f"{'🔴' if is_pred_frac else '🟢'} {prob:.1%}", fontsize=9)
    axes[i, 2].axis('off')

    # Col 3: GT mask
    axes[i, 3].imshow(vis)
    if seg_true[i].sum() > 0:
        axes[i, 3].imshow(seg_true[i,:,:,0], alpha=0.55, cmap='Reds', vmin=0, vmax=1)
    axes[i, 3].axis('off')

    # Col 4: Pred mask
    axes[i, 4].imshow(vis)
    pred_mask = sp[i,:,:,0]
    if pred_mask.max() > 0.1:
        axes[i, 4].imshow(pred_mask > 0.5, alpha=0.55, cmap='hot', vmin=0, vmax=1)
    axes[i, 4].axis('off')

plt.tight_layout()
plt.savefig('/content/05_predictions.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Saved: /content/05_predictions.png")

# 21. FINAL SUMMARY
best_auc = max(H.get('val_cls_out_auc', [0]))
best_ep  = np.argmax(H.get('val_cls_out_auc', [0])) + 1

print("\n╔" + "═"*58 + "╗")
print("║                TRAINING COMPLETE                        ║")
print("╠" + "═"*58 + "╣")
print(f"║  Original dataset : {total} images")
print(f"║  Training dataset : {len(train_data)} samples (no oversampling)")
print(f"║  Model            : FractureNet ({MODEL_CHOICE})")
print(f"║  Mixed Precision  : {tf.keras.mixed_precision.global_policy().name}")
print(f"║  Epochs run       : {n_ep} (Phase1={n_ep//2} + Phase2={n_ep//2})")
print(f"║  Best Val AUC     : {best_auc:.4f}  (epoch {best_ep})")
print(f"║  Class Weights    : NonFrac={cw[0]:.3f} | Frac={cw[1]:.3f}")
print("║")
print("║   Outputs:")
print("║    /content/best_fracturenet.keras")
print("║    /content/01_data_analysis.png")
print("║    /content/02_augmentation.png")
print("║    /content/03_training_history.png")
print("║    /content/04_confusion_matrix.png")
print("║    /content/05_predictions.png")
print("╚" + "═"*58 + "╝")

# 22. CONFUSION MATRIX PER BODY PART
print("\n" + "="*60)
print(" Detailed Analysis: Confusion Matrix by Body Part")
print("="*60)

test_bps = [d['bp'] for d in test_data]
unique_bps = sorted(list(set(test_bps)))

fig, axes = plt.subplots(1, len(unique_bps), figsize=(4.5 * len(unique_bps), 4.5))
if len(unique_bps) == 1:
    axes = [axes]
fig.suptitle(' Confusion Matrices per Body Part', fontsize=16, fontweight='bold', y=1.05)

for idx, bp in enumerate(unique_bps):
    bp_indices = [i for i, part in enumerate(test_bps) if part == bp]
    if len(bp_indices) == 0: continue

    bp_y_true = [y_true[i] for i in bp_indices]
    bp_y_pred = [y_pred[i] for i in bp_indices]

    print(f"\n{'='*20} [{bp.upper()}] {'='*20}")
    print(classification_report(bp_y_true, bp_y_pred, target_names=['Non-Fractured', 'Fractured'], zero_division=0))

    cm_bp = confusion_matrix(bp_y_true, bp_y_pred, labels=[0, 1])
    tn, fp, fn, tp = cm_bp.ravel()

    acc = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0

    sns.heatmap(cm_bp, annot=True, fmt='d', cmap='Oranges',
                xticklabels=['Non-Frac', 'Frac'],
                yticklabels=['Non-Frac', 'Frac'],
                ax=axes[idx], linewidths=0.5, cbar=False)

    title_text = f'{bp.upper()} (n={len(bp_indices)})\nAcc: {acc:.1%} | Recall: {recall:.1%}'
    axes[idx].set_title(title_text, fontweight='bold', pad=10)
    axes[idx].set_xlabel('Predicted')
    if idx == 0:
        axes[idx].set_ylabel('True')

plt.tight_layout()
plt.savefig('/content/06_cm_per_body_part.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Saved: /content/06_cm_per_body_part.png")
